// Resume Templates Registry for ResumeMkr
// Total Minimum 30 distinct professional, ATS-friendly templates

export const TEMPLATES = [
  {
    id: "modern_ats",
    name: "Modern ATS",
    category: "ATS",
    font: "Inter",
    primaryColor: "#0f172a",
    secondaryColor: "#475569",
    layout: "one-column",
    headerStyle: "centered",
    showIcons: false,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "classic",
    name: "Classic Elegant",
    category: "Classic",
    font: "Times New Roman",
    primaryColor: "#000000",
    secondaryColor: "#333333",
    layout: "one-column",
    headerStyle: "traditional",
    showIcons: false,
    showLines: true,
    margins: "24px",
    lineHeight: "1.4",
    fontSize: "13px"
  },
  {
    id: "professional",
    name: "Professional",
    category: "Professional",
    font: "Calibri",
    primaryColor: "#1e3a8a",
    secondaryColor: "#1e40af",
    layout: "one-column",
    headerStyle: "left-align",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "executive",
    name: "Executive Luxury",
    category: "Professional",
    font: "Georgia",
    primaryColor: "#1e1b4b",
    secondaryColor: "#b45309",
    layout: "two-column-right-narrow",
    headerStyle: "centered-boxed",
    showIcons: true,
    showLines: true,
    margins: "22px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "minimal",
    name: "Minimalist Light",
    category: "Minimal",
    font: "Lato",
    primaryColor: "#27272a",
    secondaryColor: "#71717a",
    layout: "one-column",
    headerStyle: "ultra-clean",
    showIcons: false,
    showLines: false,
    margins: "26px",
    lineHeight: "1.6",
    fontSize: "13px"
  },
  {
    id: "creative",
    name: "Creative Splash",
    category: "Creative",
    font: "Poppins",
    primaryColor: "#7c3aed",
    secondaryColor: "#db2777",
    layout: "two-column-left-sidebar",
    headerStyle: "creative-banner",
    showIcons: true,
    showLines: true,
    margins: "18px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "corporate",
    name: "Corporate Standard",
    category: "Professional",
    font: "Arial",
    primaryColor: "#0f172a",
    secondaryColor: "#3b82f6",
    layout: "one-column",
    headerStyle: "border-top",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.45",
    fontSize: "14px"
  },
  {
    id: "blue_professional",
    name: "Blue Professional",
    category: "Professional",
    font: "Open Sans",
    primaryColor: "#0369a1",
    secondaryColor: "#0284c7",
    layout: "one-column",
    headerStyle: "two-row",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "black_white",
    name: "Black & White ATS",
    category: "ATS",
    font: "Courier New",
    primaryColor: "#000000",
    secondaryColor: "#555555",
    layout: "one-column",
    headerStyle: "basic",
    showIcons: false,
    showLines: true,
    margins: "25px",
    lineHeight: "1.4",
    fontSize: "13px"
  },
  {
    id: "sidebar_resume",
    name: "Sidebar Compact",
    category: "Creative",
    font: "Roboto",
    primaryColor: "#111827",
    secondaryColor: "#4b5563",
    layout: "two-column-left-sidebar",
    headerStyle: "sidebar-embedded",
    showIcons: true,
    showLines: false,
    margins: "16px",
    lineHeight: "1.4",
    fontSize: "13px"
  },
  {
    id: "timeline_resume",
    name: "Timeline Centric",
    category: "Creative",
    font: "Inter",
    primaryColor: "#059669",
    secondaryColor: "#0d9488",
    layout: "one-column",
    headerStyle: "timeline-connector",
    showIcons: true,
    showLines: true,
    margins: "22px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "two_column",
    name: "Balanced Two-Column",
    category: "Professional",
    font: "Poppins",
    primaryColor: "#1e293b",
    secondaryColor: "#475569",
    layout: "two-column-equal",
    headerStyle: "centered",
    showIcons: true,
    showLines: true,
    margins: "18px",
    lineHeight: "1.5",
    fontSize: "13px"
  },
  {
    id: "one_column",
    name: "Classic One-Column",
    category: "Classic",
    font: "Times New Roman",
    primaryColor: "#111827",
    secondaryColor: "#374151",
    layout: "one-column",
    headerStyle: "left-align",
    showIcons: false,
    showLines: true,
    margins: "22px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "student_resume",
    name: "Student Starter",
    category: "Student",
    font: "Open Sans",
    primaryColor: "#0284c7",
    secondaryColor: "#0369a1",
    layout: "one-column",
    headerStyle: "centered-underlined",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "fresher_resume",
    name: "Fresher Classic",
    category: "Student",
    font: "Calibri",
    primaryColor: "#4f46e5",
    secondaryColor: "#4338ca",
    layout: "one-column",
    headerStyle: "left-align-with-bar",
    showIcons: false,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "developer_resume",
    name: "Developer Modern",
    category: "Developer",
    font: "JetBrains Mono",
    primaryColor: "#0284c7",
    secondaryColor: "#10b981",
    layout: "two-column-right-narrow",
    headerStyle: "terminal-header",
    showIcons: true,
    showLines: true,
    margins: "15px",
    lineHeight: "1.4",
    fontSize: "12px"
  },
  {
    id: "designer_resume",
    name: "Designer Minimalist",
    category: "Designer",
    font: "Poppins",
    primaryColor: "#f43f5e",
    secondaryColor: "#fb7185",
    layout: "two-column-left-sidebar",
    headerStyle: "designer-brand",
    showIcons: false,
    showLines: false,
    margins: "15px",
    lineHeight: "1.6",
    fontSize: "13px"
  },
  {
    id: "business_resume",
    name: "Business Corporate",
    category: "Professional",
    font: "Lato",
    primaryColor: "#1e3a8a",
    secondaryColor: "#f59e0b",
    layout: "one-column",
    headerStyle: "split-header",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.45",
    fontSize: "14px"
  },
  {
    id: "data_analyst_resume",
    name: "Data Analyst Pro",
    category: "Developer",
    font: "Inter",
    primaryColor: "#0f766e",
    secondaryColor: "#0284c7",
    layout: "two-column-right-narrow",
    headerStyle: "metric-focused",
    showIcons: true,
    showLines: true,
    margins: "18px",
    lineHeight: "1.45",
    fontSize: "13px"
  },
  {
    id: "manager_resume",
    name: "Manager Premium",
    category: "Professional",
    font: "Georgia",
    primaryColor: "#312e81",
    secondaryColor: "#6366f1",
    layout: "one-column",
    headerStyle: "bold-initials",
    showIcons: true,
    showLines: true,
    margins: "22px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "healthcare_resume",
    name: "Healthcare Standard",
    category: "Professional",
    font: "Arial",
    primaryColor: "#0891b2",
    secondaryColor: "#083344",
    layout: "one-column",
    headerStyle: "teal-badge",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "teacher_resume",
    name: "Teacher Warm",
    category: "Student",
    font: "Open Sans",
    primaryColor: "#d97706",
    secondaryColor: "#78350f",
    layout: "one-column",
    headerStyle: "warm-accent",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "marketing_resume",
    name: "Marketing Edge",
    category: "Creative",
    font: "Poppins",
    primaryColor: "#ec4899",
    secondaryColor: "#8b5cf6",
    layout: "two-column-left-sidebar",
    headerStyle: "gradient-text",
    showIcons: true,
    showLines: true,
    margins: "18px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "sales_resume",
    name: "Sales Closer",
    category: "Professional",
    font: "Calibri",
    primaryColor: "#1e3a8a",
    secondaryColor: "#15803d",
    layout: "one-column",
    headerStyle: "bold-sidebar-stripe",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.45",
    fontSize: "14px"
  },
  {
    id: "simple_ats",
    name: "Simple Plain ATS",
    category: "ATS",
    font: "Arial",
    primaryColor: "#000000",
    secondaryColor: "#333333",
    layout: "one-column",
    headerStyle: "centered-simple",
    showIcons: false,
    showLines: false,
    margins: "25px",
    lineHeight: "1.5",
    fontSize: "13px"
  },
  {
    id: "elegant",
    name: "Elegant Serif",
    category: "Classic",
    font: "Georgia",
    primaryColor: "#1e293b",
    secondaryColor: "#64748b",
    layout: "one-column",
    headerStyle: "italicized",
    showIcons: false,
    showLines: true,
    margins: "24px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "minimal_gray",
    name: "Minimalist Slate",
    category: "Minimal",
    font: "Inter",
    primaryColor: "#334155",
    secondaryColor: "#64748b",
    layout: "one-column",
    headerStyle: "clean-gray",
    showIcons: false,
    showLines: false,
    margins: "25px",
    lineHeight: "1.55",
    fontSize: "14px"
  },
  {
    id: "luxury",
    name: "Luxury Gold Accent",
    category: "Classic",
    font: "Times New Roman",
    primaryColor: "#1e1e24",
    secondaryColor: "#d4af37",
    layout: "two-column-right-narrow",
    headerStyle: "gold-border",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "dark_mode_resume",
    name: "Dark Cosmic",
    category: "Creative",
    font: "Poppins",
    primaryColor: "#0f172a",
    secondaryColor: "#38bdf8",
    layout: "one-column",
    headerStyle: "cosmic-dark",
    showIcons: true,
    showLines: true,
    margins: "20px",
    lineHeight: "1.5",
    fontSize: "14px"
  },
  {
    id: "colorful_resume",
    name: "Colorful Vibes",
    category: "Creative",
    font: "Lato",
    primaryColor: "#06b6d4",
    secondaryColor: "#f43f5e",
    layout: "two-column-left-sidebar",
    headerStyle: "colorful-stripes",
    showIcons: true,
    showLines: true,
    margins: "18px",
    lineHeight: "1.5",
    fontSize: "14px"
  }
];

// Recreate default resumes to allow users to build with preset template data
export const DEFAULT_RESUME_DATA = {
  name: "My Professional Resume",
  templateId: "modern_ats",
  isFavorite: false,
  tags: ["Professional", "Tech"],
  notes: "Draft prepared for senior roles.",
  personalInfo: {
    fullName: "Alex Rivera",
    jobTitle: "Senior Software Engineer",
    email: "alex.rivera@example.com",
    phone: "+1 (555) 019-2834",
    address: "San Francisco, CA",
    linkedin: "linkedin.com/in/alexrivera",
    github: "github.com/alexrivera",
    portfolio: "alexrivera.dev",
    photoURL: ""
  },
  summary: "Results-driven Senior Software Engineer with over 6 years of experience building high-performance web applications. Expertise in cloud architectures, microservices, and leading agile dev teams to deliver stellar user experiences.",
  education: [
    {
      institution: "Stanford University",
      degree: "B.S. in Computer Science",
      location: "Stanford, CA",
      startDate: "2016-09",
      endDate: "2020-06",
      gpa: "3.8",
      description: "Graduated with Honors. Specialized in Software Systems and Human-Computer Interaction."
    }
  ],
  experience: [
    {
      company: "Cloudtech Solutions",
      role: "Lead Systems Developer",
      location: "San Francisco, CA",
      startDate: "2022-08",
      endDate: "Present",
      current: true,
      description: "Designed, built, and launched reactive API services supporting over 10M active monthly users. Led a cross-functional squad of 8 engineers and improved team shipping velocity by 35%."
    },
    {
      company: "Innovate Labs",
      role: "Full Stack Engineer",
      location: "Austin, TX",
      startDate: "2020-07",
      endDate: "2022-07",
      current: false,
      description: "Developed features using TypeScript, React, and Node.js. Decreased database query latency by 45% by optimizing indexing schemes and integrating caching layers."
    }
  ],
  projects: [
    {
      title: "AgileBoard Platform",
      role: "Creator",
      link: "github.com/alexrivera/agileboard",
      description: "A collaborative Kanban board featuring real-time state synchronization, drag-and-drop lists, and automated velocity reports."
    }
  ],
  skills: {
    technical: ["React", "TypeScript", "Node.js", "Express", "Firebase", "PostgreSQL", "Docker", "AWS", "Git"],
    soft: ["Team Leadership", "Agile Methodologies", "Critical Thinking", "Product Strategy"],
    languages: ["English (Native)", "Spanish (Conversational)"]
  },
  certifications: [
    "AWS Certified Solutions Architect (2024)",
    "Certified ScrumMaster (CSM)"
  ],
  achievements: [
    "Won First Place at San Francisco TechHack 2023 for AI-driven sustainability assistant.",
    "Recognized as Innovator of the Year at Cloudtech Solutions (2024)."
  ],
  customSections: [],
  themeSettings: {
    primaryColor: "#0f172a",
    secondaryColor: "#475569",
    fontFamily: "Inter",
    fontSize: "14px",
    lineHeight: "1.5",
    margins: "20px",
    showPhoto: true,
    showIcons: true,
    showLines: true,
    pageSize: "A4"
  }
};
